name: CI/CD Build Docker Image, Push to Docker Hub, and Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: arjunkan22/cinepass-server:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Private Key for SSH
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > cinepass-server.key

      - name: Set Permissions for Private Key
        run: chmod 600 cinepass-server.key
        
      - name: Deploy to DigitalOcean Droplet
        run: |
          ssh -i "cinepass-server.key" -o StrictHostKeyChecking=no root@165.22.208.1 << 'EOF'
            # Ensure the public key is authorized on the server (if not already)
            echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
            
            # Stop and remove existing container (if any)
            sudo docker stop cinepass-server || true
            sudo docker rm cinepass-server || true
            
            # Remove old image
            sudo docker rmi arjunkan22/cinepass-server:latest || true
            
            # Pull the latest Docker image
            sudo docker pull arjunkan22/cinepass-server:latest
            
            # Run the container
            sudo docker run -d --name cinepass-server -p 3001:3001 --env-file .env arjunkan22/cinepass-server
          EOF
      
      - name: Cleanup Private Key
        run: rm cinepass-server.key
