name: CI/CD Build Docker Image, Push to Docker Hub, and Deploy to AWS EC2

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: arjunkan22/cinepass-server:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create PEM file from secret
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > cinepass-server.pem

      - name: Set permissions for PEM file
        run: chmod 600 cinepass-server.pem
        
      - name: Pull Docker image and run container
        run: |
          ssh -i "cinepass-server.pem" -o StrictHostKeyChecking=no ubuntu@ec2-3-7-66-32.ap-south-1.compute.amazonaws.com << 'EOF'
            sudo docker stop cinepass-server || true
            sudo docker rm cinepass-server || true
            sudo docker rmi arjunkan22/cinepass-server:latest || true
            sudo docker pull arjunkan22/cinepass-server:latest
            sudo docker run -d --name cinepass-server -p 3001:3001 --env-file .env arjunkan22/cinepass-server
          EOF
      
      - name: Cleanup PEM file
        run: rm cinepass-server.pem
