name: CI/CD Build Docker Image, Push to Docker Hub, and Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: arjunkan22/cinepass-server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Create the private key file from the GitHub Secrets
      - name: Create Private Key for SSH
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > cinepass-server

      # Set proper permissions for the private key file
      - name: Set Permissions for Private Key
        run: chmod 600 cinepass-server

      # Deploy to DigitalOcean droplet via SSH
      - name: Deploy to DigitalOcean droplet via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_IP4_ADDRESS }}  # Droplet IP address
          username: root  # Root user (or appropriate user with Docker permissions)
          key: cinepass-server  # Private key file created earlier
          passphrase: ${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}  # Optional if the private key requires a passphrase
          script: |

            # Stop and remove the existing Docker container
            docker stop cinepass-server || true
            docker rm cinepass-server || true

            # Remove the old Docker image
            docker rmi arjunkan22/cinepass-server:latest || true

            # Pull the latest Docker image from Docker Hub
            docker pull arjunkan22/cinepass-server:latest

            # Run the container with the latest image
            docker run -d --name cinepass-server -p 3001:3001 --env-file .env arjunkan22/cinepass-server

      # Cleanup the private key file
      - name: Cleanup Private Key
        run: rm cinepass-server
