name: >-
  CI/CD Build Docker Image, Push to Docker Hub, and Deploy to DigitalOcean
  Droplet
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 'arjunkan22/cinepass-server:latest'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Private Key for SSH
        run: 'echo "${{ secrets.SSH_PRIVATE_KEY }}" > cinepass-server.key'
      - name: Set Permissions for Private Key
        run: chmod 600 cinepass-server.key
      - name: Add Public Key to Authorized Keys on Server
        run: >
          echo ssh-ed25519
          AAAAC3NzaC1lZDI1NTE5AAAAIFP3stIr7NKBKfSAiApTvVsj/Up/QJmK9Tc5vEvLIwa8
          user@DESKTOP-TEKL851 | ssh -i cinepass-server.key -o
          StrictHostKeyChecking=no root@${{ secrets.DIGITAL_IP4_ADDRESS }}
          'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 600
          ~/.ssh/authorized_keys'
      - name: Deploy to DigitalOcean droplet via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: '${{ secrets.DIGITAL_IP4_ADDRESS }}'
          username: root
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          passphrase: '${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}'
          script: >
            docker stop cinepass-server || true

            docker rm cinepass-server || true

            docker pull arjunkan22/cinepass-server:latest

            docker run -d --name cinepass-server -p 3001:3001 --env-file .env
            arjunkan22/cinepass-server
      - name: Cleanup Private Key
        run: rm cinepass-server.key
